# Encoding: UTF-8
# DO NOT EDIT THIS FILE DIRECTLY! Instead, use lib/gemspec.rb to generate it.

Gem::Specification.new do |s|
  s.name              = %q{refinerycms}
  s.version           = %q{2.0.0}
  s.description       = %q{A Ruby on Rails CMS that supports Rails 3. It's easy to extend and sticks to 'the Rails way' where possible.}
  s.date              = %q{2011-10-12}
  s.summary           = %q{A Ruby on Rails CMS that supports Rails 3}
  s.email             = %q{info@refinerycms.com}
  s.homepage          = %q{http://refinerycms.com}
  s.rubyforge_project = %q{refinerycms}
  s.authors           = ['Resolve Digital', 'Philip Arndt', 'David Jones', 'Steven Heidel', 'Uģis Ozols']
  s.license           = %q{MIT}
  s.require_paths     = %w(lib)
  s.executables       = %w(refinerycms)

  # Bundler
  s.add_dependency    'bundler',                    '~> 1.0'

  # Refinery CMS
  s.add_dependency    'refinerycms-authentication', '= 2.0.0'
  s.add_dependency    'refinerycms-base',           '= 2.0.0'
  s.add_dependency    'refinerycms-core',           '= 2.0.0'
  s.add_dependency    'refinerycms-dashboard',      '= 2.0.0'
  s.add_dependency    'refinerycms-images',         '= 2.0.0'
  s.add_dependency    'refinerycms-pages',          '= 2.0.0'
  s.add_dependency    'refinerycms-resources',      '= 2.0.0'
  s.add_dependency    'refinerycms-settings',       '= 2.0.0'

  s.files             = [
    '.gitignore',
    '.rspec',
    '.yardopts',
    'Gemfile',
    'Guardfile',
    'Rakefile',
    'bin',
    'bin/refinerycms',
    'changelog.md',
    'config',
    'config/database.yml.mysql',
    'config/database.yml.postgresql',
    'config/database.yml.sqlite3',
    'config/environments',
    'config/environments/development.rb',
    'config/environments/production.rb',
    'config/environments/test.rb',
    'config/routes.rb',
    'config.ru',
    'lib',
    'lib/load_path_analyzer.rb',
    'lib/refinery.rb',
    'lib/refinerycms',
    'lib/refinerycms/all.rb',
    'lib/refinerycms.rb',
    'license.md',
    'public',
    'public/javascripts',
    'public/javascripts/translations.js',
    'readme.md',
    'refinerycms.gemspec'
  ]
end
