source "http://rubygems.org"

gemspec

## Uncomment the following lines to develop against a local clone of refinery
# gem 'refinerycms', :path => '~/Code/refinerycms'
# gem 'refinerycms-generators', :path => '~/Code/refinerycms-generators'
# gem 'seo_meta', :git => 'git://github.com/parndt/seo_meta.git'

gem 'jquery-rails'

group :development, :test do  
  require 'rbconfig'
  
  platforms :mswin, :mingw do
    gem 'win32console'
    gem 'rb-fchange', '~> 0.0.5'
    gem 'rb-notifu', '~> 0.0.4'
  end

  platforms :ruby do
    gem 'spork', '0.9.0.rc9'
    gem 'guard-spork'
    
    if Config::CONFIG['target_os'] =~ /darwin/i
      gem 'rb-fsevent', '>= 0.3.9'
      gem 'growl',      '~> 1.0.3'
    end
    if Config::CONFIG['target_os'] =~ /linux/i
      gem 'rb-inotify', '>= 0.5.1'
      gem 'libnotify',  '~> 0.1.3'
    end
  end

  platforms :jruby do
    if Config::CONFIG['target_os'] =~ /darwin/i
      gem 'growl',      '~> 1.0.3'
    end
    if Config::CONFIG['target_os'] =~ /linux/i
      gem 'rb-inotify', '>= 0.5.1'
      gem 'libnotify',  '~> 0.1.3'
    end
  end
end

group :assets do
  gem 'sass-rails', "~> 3.1.0.rc"
  gem 'coffee-rails', "~> 3.1.0.rc"
  gem 'uglifier'
end
