#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

unless File.exist?(db_yml = File.expand_path('../config/database.yml', __FILE__))
  require 'fileutils'
  FileUtils.cp "#{db_yml}.sqlite3", db_yml
  puts "Copied #{db_yml}.sqlite3 to #{db_yml}"
end

require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks
