#!/usr/bin/env ruby
require File.expand_path('../../base/lib/refinery.rb', __FILE__)
files = %w( Gemfile *.md **/**/{*,.rspec,.gitignore,.yardopts} ).map { |file| Dir.glob(file) }.flatten.sort
rejection_patterns = [
  "^(authentication|base|core|dashboard|images|pages|resources|settings)",
  "^public/system",
  "^config/(application|boot|environment).rb$",
  "^config/initializers(\/.*\.rb)?$",
  "^config/(database|i18n\-js).yml$",
  "^lib\/gemspec\.rb",
  ".*\/cache\/",
  "^db\/(schema|seeds|.*\.sqlite3?(-journal)?|migrate)(\/?.*\.rb)?$",
  "^script\/*",
  "^vendor\/plugins\/?$",
  "(^log|\.log)$",
  "\.rbc$",
  "^tmp(|/.+?)$",
  ".gem$",
  "^doc($|\/)"
]

files.reject! do |f|
  !File.exist?(f) or f =~ %r{(#{rejection_patterns.join(')|(')})} or (File.directory?(f) and Dir[File.join(f, "*")].empty?)
end

gemspec = <<EOF
# DO NOT EDIT THIS FILE DIRECTLY! Instead, use lib/gemspec.rb to generate it.

Gem::Specification.new do |s|
  s.name              = %q{refinerycms}
  s.version           = %q{#{Refinery.version}}
  s.description       = %q{A Ruby on Rails CMS that supports Rails 3. It's easy to extend and sticks to 'the Rails way' where possible.}
  s.date              = %q{#{Time.now.strftime('%Y-%m-%d')}}
  s.summary           = %q{A Ruby on Rails CMS that supports Rails 3}
  s.email             = %q{info@refinerycms.com}
  s.homepage          = %q{http://refinerycms.com}
  s.rubyforge_project = %q{refinerycms}
  s.authors           = ['Resolve Digital', 'David Jones', 'Philip Arndt']
  s.license           = %q{MIT}
  s.require_paths     = %w(lib)
  s.executables       = %w(#{Dir.glob('bin/*').map{|d| d.gsub('bin/','')}.join(' ')})

  # Bundler
  s.add_dependency    'bundler',                    '~> 1.0.5'

  # Refinery CMS
  s.add_dependency    'refinerycms-generators',     '~> 0.9.9.3'
  s.add_dependency    'refinerycms-authentication', '~> 0.9.9'
  s.add_dependency    'refinerycms-base',           '~> 0.9.9'
  s.add_dependency    'refinerycms-core',           '~> 0.9.9'
  s.add_dependency    'refinerycms-dashboard',      '~> 0.9.9'
  s.add_dependency    'refinerycms-images',         '~> 0.9.9'
  s.add_dependency    'refinerycms-pages',          '~> 0.9.9'
  s.add_dependency    'refinerycms-resources',      '~> 0.9.9'
  s.add_dependency    'refinerycms-settings',       '~> 0.9.9'

  s.add_development_dependency 'rspec-rails',       '~> 2.5'

  # Cucumber
  s.add_development_dependency 'capybara',          '>= 0.4.1.1'
  s.add_development_dependency 'database_cleaner'
  s.add_development_dependency 'cucumber-rails'
  s.add_development_dependency 'cucumber'
  s.add_development_dependency 'launchy'
  s.add_development_dependency 'gherkin'
  s.add_development_dependency 'rack-test',         '~> 0.5.6'
  s.add_development_dependency 'json_pure'

  # Factory Girl
  s.add_development_dependency 'factory_girl'

  # Autotest
  s.add_development_dependency 'autotest'
  s.add_development_dependency 'autotest-rails'
  s.add_development_dependency 'autotest-notification'

  s.files             = [
    '#{files.sort.join("',\n    '")}'
  ]
end
EOF

File.open(File.expand_path("../../refinerycms.gemspec", __FILE__), 'w').puts(gemspec)
