# DO NOT EDIT THIS FILE DIRECTLY! Instead, use lib/gemspec.rb to generate it.

Gem::Specification.new do |s|
  s.name              = %q{refinerycms-layouts}
  s.version           = %q{0.9.9.21}
  s.summary           = %q{Per entity layouts for refinerycms}
  s.description       = %q{This module lets you select the layout template to use for a given page instead of being tied to the application.html.erb layout.}
  s.date              = %q{2011-05-21}
  s.email             = %q{info@refinerycms.com}
  s.homepage          = %q{http://refinerycms.com}
  s.rubyforge_project = %q{refinerycms}
  s.authors           = ['Vaughn Draughon']
  s.license           = %q{MIT}
  s.require_paths     = %w(lib)
  s.executables       = %w()

  s.files             = [
    'config',
    'config/locales',
    'config/locales/en.yml',
    'config/locales/lolcat.yml',
    'config/locales/nb.yml',
    'config/locales/nl.yml',
    'config/routes.rb',
    'db',
    'db/migrate',
    'db/migrate/1_create_layouts.rb',
    'db/migrate/2_create_page_templates.rb',
    'db/seeds',
    'db/seeds/layouts.rb',
    'lib',
    'lib/gemspec.rb',
    'lib/generators',
    'lib/generators/refinerycms_layouts_generator.rb',
    'lib/refinerycms-layouts.rb',
    'lib/tasks',
    'lib/tasks/layouts.rake',
    'readme.md',
    'refinerycms-layouts.gemspec',
    'spec',
    'spec/layouts_spec.rb'
  ]

  s.add_dependency 'refinerycms-core',            '= 0.9.9.21'
end
