require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

desc 'Generate documentation for the Refinery Theme Generator plugin.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'Refinery Theme Generator'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README')
end